name: Feature Request
description: Suggest an idea or enhancement for EnterpriseHub
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the form below to help us understand your idea.

  - type: dropdown
    id: module
    attributes:
      label: Module Affected
      description: Which module does this feature relate to?
      options:
        - Jorge Bots (Lead/Buyer/Seller)
        - BI Dashboard (Streamlit)
        - FastAPI Backend (Routes/API)
        - GHL CRM Integration
        - AI Orchestration (Claude/Gemini)
        - ML Scoring Engines
        - RAG Pipeline
        - Voice AI (Retell/Vapi)
        - Stripe Billing
        - Agent Mesh / Swarm
        - DevOps / Docker / CI
        - Core/Utils
        - New Module
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: A clear and concise description of what problem this feature would solve.
      placeholder: |
        I'm always frustrated when...

        Currently, the application doesn't allow me to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        I would like to be able to...

        The feature would work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: |
        I've also considered...

        Another way to solve this could be...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Critical/Blocking
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, examples, or screenshots about the feature request here.
      placeholder: |
        Here's an example of how this could look...

        Similar features in other tools...
    validations:
      required: false
