"""
ROIEngine Service for GHL Real Estate AI.
Calculates "Value Generated" for swarm executions and logs ROI milestones.
"""
from typing import Dict, Any, Optional
from datetime import datetime
from ghl_real_estate_ai.agent_system.hooks.governance import governance_auditor
from ghl_real_estate_ai.agents.blackboard import SharedBlackboard
from ghl_real_estate_ai.ghl_utils.logger import get_logger

logger = get_logger(__name__)

# Constants for ROI calculation
TIME_SAVED_VALUE_PER_HOUR = 50.0  # $50/hr for administrative/agent time
ESTIMATED_CONVERSION_LIFT_VALUE = 500.0  # $500 estimated value per AI-matched property lead

class ROIEngine:
    """
    Calculates and logs the Return on Investment for AI operations.
    """
    def __init__(self, blackboard: Optional[SharedBlackboard] = None):
        self.blackboard = blackboard

    def calculate_swarm_roi(self, swarm_stats: Dict[str, Any], agent_name: str = "ROIEngine") -> Dict[str, Any]:
        """
        Calculates the value generated by a swarm execution.
        
        Args:
            swarm_stats: Statistics from the swarm run (tasks completed, time taken, matches found, etc.)
            agent_name: Name of the agent reporting ROI
            
        Returns:
            ROI metrics dictionary
        """
        tasks_completed = swarm_stats.get("tasks_completed", 0)
        time_saved_minutes = tasks_completed * 10  # Estimate 10 mins saved per task
        time_saved_hours = time_saved_minutes / 60.0
        time_saved_value = time_saved_hours * TIME_SAVED_VALUE_PER_HOUR
        
        matches_found = swarm_stats.get("matches_found", 0)
        conversion_lift_value = matches_found * ESTIMATED_CONVERSION_LIFT_VALUE
        
        total_value = time_saved_value + conversion_lift_value
        
        roi_metrics = {
            "timestamp": datetime.now().isoformat(),
            "tasks_completed": tasks_completed,
            "time_saved_hours": round(time_saved_hours, 2),
            "time_saved_value": round(time_saved_value, 2),
            "matches_found": matches_found,
            "conversion_lift_value": round(conversion_lift_value, 2),
            "total_value_generated": round(total_value, 2)
        }
        
        # Write to blackboard if available
        if self.blackboard:
            self.blackboard.write("swarm_roi_metrics", roi_metrics, agent_name)
            
        # Log ROI Milestone to Audit Manifest
        self.log_roi_milestone(roi_metrics)
        
        return roi_metrics

    def log_roi_milestone(self, metrics: Dict[str, Any]):
        """Logs an ROI milestone to the governance auditor."""
        try:
            governance_auditor.log_roi_milestone(metrics)
        except Exception as e:
            logger.error(f"Failed to log ROI milestone: {e}")

# Global instance
roi_engine = ROIEngine()
