"""
ROIEngine Service for GHL Real Estate AI.
Calculates "Value Generated" for swarm executions and logs ROI milestones.
"""

import asyncio
from datetime import datetime
from typing import Any, Dict, List, Optional

from ghl_real_estate_ai.agent_system.hooks.governance import governance_auditor
from ghl_real_estate_ai.agents.blackboard import SharedBlackboard
from ghl_real_estate_ai.ghl_utils.logger import get_logger
from ghl_real_estate_ai.services.database_service import get_database

logger = get_logger(__name__)

# Constants for ROI calculation
TIME_SAVED_VALUE_PER_HOUR = 50.0  # $50/hr for administrative/agent time
ESTIMATED_CONVERSION_LIFT_VALUE = 500.0  # $500 estimated value per AI-matched property lead
DEFAULT_COMMISSION_RATE = 0.025  # 2.5% default commission


class ROIEngine:
    """
    Calculates and logs the Return on Investment for AI operations.
    Integrates with PostgreSQL for persistent value tracking.
    """

    def __init__(self, blackboard: Optional[SharedBlackboard] = None):
        self.blackboard = blackboard
        self._db = None

    async def _get_db(self):
        if not self._db:
            self._db = await get_database()
        return self._db

    async def calculate_swarm_roi(self, swarm_stats: Dict[str, Any], agent_name: str = "ROIEngine") -> Dict[str, Any]:
        """
        Calculates the value generated by a swarm execution.

        Args:
            swarm_stats: Statistics from the swarm run (tasks completed, time taken, matches found, lead_ids, etc.)
            agent_name: Name of the agent reporting ROI

        Returns:
            ROI metrics dictionary
        """
        tasks_completed = swarm_stats.get("tasks_completed", 0)
        time_saved_minutes = tasks_completed * 10  # Estimate 10 mins saved per task
        time_saved_hours = time_saved_minutes / 60.0
        time_saved_value = time_saved_hours * TIME_SAVED_VALUE_PER_HOUR

        matches_found = swarm_stats.get("matches_found", 0)
        conversion_lift_value = matches_found * ESTIMATED_CONVERSION_LIFT_VALUE

        # Calculate potential revenue from lead CLV
        lead_ids = swarm_stats.get("lead_ids", [])
        clv_revenue = 0.0
        if lead_ids:
            clv_revenue = await self._calculate_clv_impact(lead_ids)

        total_value = time_saved_value + conversion_lift_value + clv_revenue

        roi_metrics = {
            "timestamp": datetime.now().isoformat(),
            "tasks_completed": tasks_completed,
            "time_saved_hours": round(time_saved_hours, 2),
            "time_saved_value": round(time_saved_value, 2),
            "matches_found": matches_found,
            "conversion_lift_value": round(conversion_lift_value, 2),
            "clv_impact_value": round(clv_revenue, 2),
            "total_value_generated": round(total_value, 2),
        }

        # Write to blackboard if available
        if self.blackboard:
            self.blackboard.write("swarm_roi_metrics", roi_metrics, agent_name)

        # Log ROI Milestone to Audit Manifest
        self.log_roi_milestone(roi_metrics)

        # Persist to database
        if lead_ids:
            await self._record_outcomes(lead_ids, total_value)

        return roi_metrics

    async def _calculate_clv_impact(self, lead_ids: List[str]) -> float:
        """Calculates the expected revenue impact based on lead CLV predictions."""
        db = await self._get_db()
        total_impact = 0.0

        try:
            async with db.get_connection() as conn:
                rows = await conn.fetch(
                    """
                    SELECT predicted_clv_12_month, probability_of_conversion
                    FROM lead_clv_predictions
                    WHERE lead_id = ANY($1)
                """,
                    lead_ids,
                )

                for row in rows:
                    # Impact = Predicted CLV * Probability of Conversion
                    impact = float(row["predicted_clv_12_month"]) * float(row["probability_of_conversion"])
                    total_impact += impact

        except Exception as e:
            logger.error(f"Failed to calculate CLV impact: {e}")

        return total_impact

    async def _record_outcomes(self, lead_ids: List[str], total_value: float):
        """Records the ROI outcome for each lead in the model_outcomes table."""
        db = await self._get_db()
        value_per_lead = total_value / len(lead_ids) if lead_ids else 0

        try:
            async with db.transaction() as conn:
                for lead_id in lead_ids:
                    await conn.execute(
                        """
                        INSERT INTO model_outcomes (lead_id, outcome, monetary_value)
                        VALUES ($1, $2, $3)
                    """,
                        lead_id,
                        "swarm_interaction",
                        value_per_lead,
                    )
        except Exception as e:
            logger.error(f"Failed to record model outcomes: {e}")

    def log_roi_milestone(self, metrics: Dict[str, Any]):
        """Logs an ROI milestone to the governance auditor."""
        try:
            governance_auditor.log_roi_milestone(metrics)
        except Exception as e:
            logger.error(f"Failed to log ROI milestone: {e}")


# Global instance
roi_engine = ROIEngine()
